'use strict'

module.exports = {
    INITIALIZE: "INITIALIZE",
    ADD_TASK: "ADD_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    ADD_TIMER_CONFIGURATION: "ADD_TIMER_CONFIGURATION",
    UPDATE_TIMER_CONFIGURATION: "UPDATE_TIMER_CONFIGURATION",
    DELETE_TIMER_CONFIGURATION: "DELETE_TIMER_CONFIGURATION",
    COMPLETE_TASK: "COMPLETE_TASK",
    LOG_TASK_DURATION: "LOG_TASK_DURATION"
}